// Copyright 2017 Semmle Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under
// the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the License for the specific language governing
// permissions and limitations under the License.

/**
 * @name Use of a predictable seed in a secure random number generator
 * @description Using a predictable seed in a pseudo-random number generator can lead to predictability of the numbers generated by it.
 * @kind problem
 * @problem.severity error
 * @precision high
 * @id java/predictable-seed
 * @tags security
 */
import java
import semmle.code.java.security.Random

from GetRandomData da, RValue use, PredictableSeedExpr source
where
  da.getQualifier() = use and
  unsafelySeeded(use, source)
select da, "Usage of a SecureRandom number generator seeded with a $@.",
  source, "predictable value"
